/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.semnatic.reasoner;

public class Main {

    public static void main(String[] args) {
        System.out.println("START IMPLEMENTING");
    }
}
