/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.5.0
// source: src/QueryService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./QueryService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QueryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QueryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.QueryRequest,
 *   !proto.QueryResponse>}
 */
const methodDescriptor_QueryService_receiveQuery = new grpc.web.MethodDescriptor(
  '/QueryService/receiveQuery',
  grpc.web.MethodType.UNARY,
  proto.QueryRequest,
  proto.QueryResponse,
  /**
   * @param {!proto.QueryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.QueryResponse.deserializeBinary
);


/**
 * @param {!proto.QueryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.QueryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.QueryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QueryServiceClient.prototype.receiveQuery =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QueryService/receiveQuery',
      request,
      metadata || {},
      methodDescriptor_QueryService_receiveQuery,
      callback);
};


/**
 * @param {!proto.QueryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.QueryResponse>}
 *     Promise that resolves to the response
 */
proto.QueryServicePromiseClient.prototype.receiveQuery =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QueryService/receiveQuery',
      request,
      metadata || {},
      methodDescriptor_QueryService_receiveQuery);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.QueryRequest>}
 */
const methodDescriptor_QueryService_sendQuery = new grpc.web.MethodDescriptor(
  '/QueryService/sendQuery',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.QueryRequest,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.QueryRequest.deserializeBinary
);


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.QueryRequest)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.QueryRequest>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QueryServiceClient.prototype.sendQuery =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QueryService/sendQuery',
      request,
      metadata || {},
      methodDescriptor_QueryService_sendQuery,
      callback);
};


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.QueryRequest>}
 *     Promise that resolves to the response
 */
proto.QueryServicePromiseClient.prototype.sendQuery =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QueryService/sendQuery',
      request,
      metadata || {},
      methodDescriptor_QueryService_sendQuery);
};


module.exports = proto;

