/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.semnatic.reasoner;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
 

class DatabaseTests {

    @Test
    public void testDatabaseRead(){
        assertEquals(1,1);
    }
}


